package com.makeshaadi

import android.annotation.SuppressLint
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.appcompat.widget.Toolbar
import kotlinx.android.synthetic.main.activity_policy.*

class PolicyActivity : AppCompatActivity() {

    @SuppressLint("SetTextI18n")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_policy)
        setSupportActionBar(pToolbar as Toolbar)

        supportActionBar?.setDisplayHomeAsUpEnabled(true)
        supportActionBar?.setDisplayShowHomeEnabled(true)

        val type = intent.getStringExtra("type")

        if (type != null && type == "pp") {
            supportActionBar?.title = "Privacy Policy"
            pContentText.text =
                "Makeshaadi is a digital website & mobile application targeting to provide matrimonial alliance services. We ensure to protect the privacy of the users as per our terms and conditions.\n" +
                        "Once you have registered to our website/mobile app as a user/member, you accept our full terms and conditions and must provide us with the mandatory information. We aim to protect your personal information through internal and technical security measures. However, please also remember that we cannot guarantee that the internet itself is 100% secure. Once your information is in our possession, we adhere to security guidelines protecting it against unauthorised access.\n" +
                        "We use a secure server for data storage of our members & credit card transactions to protect the credit card information of our users and Cookies are used to store the login information.  We do not control the use of cookies by third parties. You may or may not provide information that is marked as not mandatory. The users are solely responsible for maintaining the confidentiality of the User Name and User Password and other activities related to transmission/transactions using their own user identity/name. They shall be solely responsible for carrying out any online or off- line transactions that involves credit/debit cards or any other forms of device or documents for making such transactions. www.makeshaadi.com accepts no accountability / liability of your act and your improper use of information relating to credit/debit cards usage whether online/offline.\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "Makeshaadi.com is securely connected to service partners, which includes servers/administrators. Your IP address and other information including Email address, Contact name, User name and password, Address, Pin code, Contact number or other contact details etc; may be used for the general administration of the website/mobile app. Your IP address may also be used for the purpose of gathering broad demographic information. The information will solely be used by us to inform you and deliver information that might be of your interests. This information may include banner advertisements, administrative notifications, product hand-outs, and communications which are relevant for you where using the website/app is concerned. Your acceptance to our terms and condition and privacy policy specify that you are willing to receive such information.\n" +
                        "\n" +
                        "User/Member Privacy \n" +
                        "Information gathered from the users will not be shared, sell, rent, trade or give away or share with any third party without the consent of the user. A member/user who wish to contact with any individual can contact with direct mobile number or with direct messaging option in the mobile app. User/member can change picture privacy anytime. User/member can schedule meetups at their desired locations with thier respected families. Makeshaadi.com does not take any responsibility of any user/member information provided in profile or in conversation is provided by the members and Makeshaadi.com do not authenticate any information and shall not be held responsible, You should inquire by yourself before proceeding further for the marriage. \n" +
                        "Makeshaadi.com does not claim any responsibility for any errors or inconsistencies. But we are committed to ensure that the proper assistance and service will be provided.\n" +
                        "Makeshaadi.com disclaims any and all responsibility or liability for the accuracy, content, completeness, legitimacy, consistency, or operability or accessibility of information or matter advertised on this website/app by third parties.\n" +
                        "Makeshaadi.com, respects the privacy of our users. This document outlines the types of personal information that is received and collected by www.Makeshaadi.com and its usage.\n" +
                        "\n" +
                        "Cookies & log files\n" +
                        "www.Halalrishtey.com use cookies to store information about visitor's preferences, record user-specific information such as pages the user accessed or visited, customize Web page content based on user's browser type or other information that the user sends via their browser.\n" +
                        "makeshaadi.com uses log files that includes information such as IP addresses type of browser used, Internet Service Provider ( ISP ), date/time, exit pages, frequency of clicks to evaluate trends, manage the site, track user's movement in the site, and collect demographic information. IP addresses and other related information are not linked to any information that might identify an individual personally.\n" +
                        "Note : The privacy policy may be changed from time to time without any prior notice. It is at your disposal to review our privacy policy periodically, for any changes made to improve the service of the website/app. However, we will update once through our means of communication.\n"
        } else {
            supportActionBar?.title = "Terms of Service"
            pContentText.text = "Welcome to Makeshaadi :\n" +
                    " Please read the terms of use for this website/app carefully. In accordance with this terms and conditions, the users of Make shaadi are provided with limited license to use the service and content of this website. The Information Technology Act, 2000 and rules there under pertaining to electronic records as applicable and amended. This electronic record is generated by a computer system and does not require any physical or digital signatures. This agreement is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011. \n" +
                    "By signing up/registering the service, you give your acceptance to be bound by the Terms and conditions (herein referred to as \"Agreement\"). To become a member of this website/app and to be able to communicate with fellow members, you must register as a member and follow the instructions given during the Registration process. This Agreement outlines the terms that you are subjected to as a member of this website/app. The Agreement may be revised from time to time at the sole discretion of makeshaadi.com and will be intimated to you Pursuant to such changes, if you continue to use the site then it will be constituted as your acceptance for the changes. \n" +
                    "Criteria to use :\n" +
                    "Make Shaadi is only to facilitate personal advertisement for lawful marriage alliance between persons who are legally competent to enter into matrimony under the laws to which they are subject. \n" +
                    "You are at least 18+ for females and 21+ for males years of age. The membership of those users will be declined whose eligibility does not match the criteria. Using this site will determine that you possess the right, authority and competence to sign this Agreement and to be bound by the terms of use of this Agreement. \n" +
                    "This site does not encourage and/or promote illegitimate sexual relations or affairs outside marriage. If any member is found to be using this site as a means of promoting or indulging or engaging in any illegitimate sexual relations or affairs outside marriage or if Makeshaadi.com becomes aware of such activities then the membership of the particular user will be terminated without any refund. Makeshaadi.com is not bound by any liability towards such individual. The binding and final termination will be the sole discretion of Makeshaadi.com.\n" +
                    "Terms of use : \n" +
                    "This Agreement will come into effect once you have registered as a member and will remain in full force as and when you continue to use the usage. If you wish to terminate your membership for any reason and at anytime, you may do so by informing  administrative in writing. In the event of administrative terminating your membership or you terminate your membership, you will not be entitled any refund irrespective of whether you have any unutilized subscription fees. Makeshaadi.com reserves the sole right to terminate your access to the Site and/or your membership for any reason. You will be intimated of the same via email at the email address (or any other email address that you may later provide) you provided in your application for membership to Makeshaadi.com. In the event of Makeshaadi.com terminating your membership for breaching the Agreement, you will not be entitled to any refund. Even after the termination of the Agreement, provisions including sections 4,5,7,9 -12 of this Agreement will remain in effect. \n" +
                    "Non commercial use of members :\n" +
                    "The service of this website/app is for the personal use of individual members only Members of Makeshaadi.com will not use the services of the website/app for any commercial purpose including link building of any kind irrespective of whether it may be deemed competitive to Makeshaadi.com or otherwise. The membership of this website/app is restricted to individuals only therefore, non-individual entity may not become members of Makeshaadi.com. Appropriate legal action will be taken against illegitimate and/or unauthorized use of the Site, which may include unauthorized framing of or linking to the Site. \n" +
                    "Members of the website/app will not engage in any advertising or solicitation of selling or buying any services or products through this website/app. You will not send any chain letters or Spam the inbox of Makeshaadi members. Using any information obtained from this service for the purpose of harassing, abusing or harming a fellow member will be considered as the violation of this agreement. Makeshaadi.com has the sole right to restrict the number of communications of all the members in order to protect its members from any sort of abuse or misuse. Sending obscene, lewd, licentious, defamatory messages that promote hatred and/or are racial or abusive in any manner will be deemed as a breach of this agreement and shall be entitled to termination of your membership. Makeshaadi.com at its own discretion reserves the right to screen messages that are sent to other Member(s). We also regulate the number of your chat sessions. Use of Bats, EXE's, CGI or any other programs/scripts to view content on or communicate/contact/respond/interact with Makeshaadi.com and/or its Members is restricted.  \n" +
                    "Propriety rights :\n" +
                    "The propriety rights of this website/app are owned by Nikahalal Services Pvt Ltd and retain all intellectual property without any limitation. The proprietary information shall not be copied, modified, published, transmitted, distributes, displayed, sold or performs in any form. Makeshaadi.com website/app possesses copyrighted material, trademarks, and other proprietary information Ownership of content posted on the Site. \n" +
                    "You agree that :\n" +
                    "1. Makeshaadi.com owns all the lawful, legal and non-objectionable messages, content and/or other information, content or material that are posted on the forum boards. \n" +
                    "2. All such information, content and/or material posted on the forum boards may be scrutinized by Makeshaadi.com and have the sole right at its own discretion to remove, edit and/or display such information, material and/or content, messages, photos or profiles which might be deemed as offensive, illegitimate, derogatory, obscene, libelous, or that might violate the rights, harm, or intimidate the safety of other members. It will be considered as a breach of this agreement and may be liable to termination. \n" +
                    "3. The Content/information that are published or displayed on the Site/app by you will be at your sole discretion. Makeshaadi.com reserves the right to verify the authenticity of Content/information posted on the Site/app and may ask you to provide any documentary or other form of evidence supporting the Content/information you post on the Site/app. \n" +
                    "4. In the event of your failure to produce such evidence, or if the evidence is not sufficient to support and justify your claim then Makeshaadi.com may, in its sole discretion, terminate your Membership without any refund. \n" +
                    "5. You understand that by posting content to any public forum, you automatically grant Makeshaadi.com and other members the license to utilize, reproduce, exhibit, distribute and perform the information and content in any manner. \n" +
                    "6. We are against dowry. Help us to make dowry free society by not demanding dowry. We request you to stand against dowry.\n" +
                    "7. The information, photos and contact numbers of the members should not be shared with anyone else or Brokerage of profiles are strictly prohibited can be booked under illegal usage of platform. You have to immediately discard once you feel you are not interested in that profile.\n" +
                    "8. Any misbehavior with the executives, staff or any our member shall lead to cancellation of the membership without refund. \n" +
                    "9. You as a member have appointed/authorize Makeshaadi.com to search, counsel and communicate the proposal and does not have any objection in sharing your profile, photos and contact information with others through our system or any other means of communication.\n" +
                    "10. If a member finds the alliance he/she shall inform us immediately so that we can remove his/her profile from our database.\n" +
                    "Copyright policy :\n" +
                    "The copyrighted material, trademarks, or other proprietary information may not be copied, reproduced or distributed in any form without the prior written consent of the owner. In the event of your copyright materials being copied and posted, you may get in touch with our copyright Agents for copyright infringement with an electronic or physical signature authorizing the person to act on behalf of the owner and a description of the copyrighted material that you believe has been infringed. You must also include the source of the material, your address, telephone number, and email address along with a written statement. If applicable then you may also produce a certificate of the registration or any other intellectual property right. \n" +
                    "Privacy :\n" +
                    "The use of this service is governed by the Halalrishteycom Privacy Policy. \n" +
                    "Disclaimers :\n" +
                    "Makeshaadi.com does not claim any responsibility for the authenticity of the Content/information posted on the Site/app, whether caused by users visiting the Site/app, Members or by any equipment or programming associated with or utilized in the Service. Furthermore, Makeshaadi does not claim any responsibility for the conduct of any user and/or Member whether online or offline. Makeshaadi.com assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, user and/or Member communications. The exchange of profile(s) through or by Makeshaadi.com should not in any way be construed as any offer and/or recommendation from/by Makeshaadi.com, The Site/app and the Service are provided \"AS-IS AVALAIBLE BASIS\" and Makeshaadi.com expressly disclaims any warranty of fitness for a particular purpose or non-infringement. Makeshaadi.com cannot guarantee and does not promise any specific results from use of the Site/app and/or the Makeshaadi.com Service. \n" +
                    "Limitation on liability :\n" +
                    "Except in jurisdiction where such provisions are limited, in any event, Makeshaadi.com will not be liable to you or any third person for any indirect, consequential, exemplary, incidental, special or punitive damages, including also lost profits arising from your use of the Site/app. Notwithstanding anything to the contrary contained herein, Makeshaadi.com, liability to you for any cause whatsoever, and regardless of the form of the action, will at all times be limited to the amount paid, if any, by you to Makeshaadi.com, for the Service during the term of membership.\n"
        }
    }
}
